// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using courseapply.Models;

#nullable disable

namespace courseapply.Migrations
{
    [DbContext(typeof(ContextModel))]
    [Migration("20240715072137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("courseapply.Models.VariableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adi")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("kayitOlduguTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("kursSecimi")
                        .HasColumnType("TEXT");

                    b.Property<string>("soyadi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("yasi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kurs");
                });
#pragma warning restore 612, 618
        }
    }
}
